//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appUcleus2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;

    [DataContract(IsReference = true)]
    public partial class calificaciones
    {
        public int idCalificacion { get; set; }
        public decimal calificacion { get; set; }
        public int fkUsuario { get; set; }
        public int fkNegocio { get; set; }
        public System.DateTime fecha { get; set; }

        [ScriptIgnore]
        public virtual negocios negocios { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
