//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appUcleus2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class negocios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public negocios()
        {
            this.calificaciones = new HashSet<calificaciones>();
            this.productos = new HashSet<productos>();
            this.usuarios1 = new HashSet<usuarios>();
            this.ventas = new HashSet<ventas>();
        }
    
        public int idNegocio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string imgNegocio { get; set; }
        public string calle { get; set; }
        public int numero { get; set; }
        public string colonia { get; set; }
        public string ciudad { get; set; }
        public Nullable<int> codigoPostal { get; set; }
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public int fkUsuario { get; set; }
        public Nullable<decimal> precioEnvio { get; set; }
        public Nullable<bool> permitePagosTarjeta { get; set; }
        public Nullable<bool> activo { get; set; }
        public string correo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calificaciones> calificaciones { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos> productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios> usuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventas> ventas { get; set; }
    }
}
